<?php

namespace Xapi\FsManager\DependencyInjection;

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Extension\Extension;
use Symfony\Component\DependencyInjection\Loader\XmlFileLoader;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

class XapiFSManagerExtension extends Extension
{
    /**
     * @throws \Exception
     */
    public function load(array $configs, ContainerBuilder $container){
        $configuration = new Configuration();
        $config = $this->processConfiguration($configuration,$configs);
        $container->setParameter("xapi.fs_manager.config",$config);
        $container->setParameter("xapi.fs_manager.root_folder",$config["root_folder"]);
        $loader = new YamlFileLoader( $container, new FileLocator(__DIR__.'/../../config'));
        $loader->load('services.yaml');
    }

    public function getAlias()
    {
        return "xapi_fs_manager"; // TODO: Change the autogenerated stub
    }
}