services:
  Xapi\FSManager\XapiFSManagerBundle:
    public: true

  Xapi\FSManager\Controllers\SnapshotController:
    public: true
    arguments:
      - '@event_dispatcher'
      - '@Xapi\FSManager\Snapshot\SnapshotWalker'
      - '@twig'

  Xapi\FSManager\Snapshot\SnapshotWalker:
    public: true
    arguments:
      - '@Xapi\FSManager\Snapshot\ScopedWalker'

  Xapi\FSManager\Snapshot\Walker:
    public: true

  Xapi\FSManager\Snapshot\ScopedWalker:
    public: true
    arguments:
      - '@Xapi\FSManager\Snapshot\Walker'
      - '%xapi.fs_manager.root_folder%'
