services:
  Xapi\FsManager\XapiFSManagerBundle:
    public: true

  Xapi\FsManager\Controllers\SnapshotController:
    public: true
    arguments:
      - '@event_dispatcher'
      - '@Xapi\FsManager\Snapshot\SnapshotWalker'
      - '@serializer'

  Xapi\FsManager\Snapshot\SnapshotWalker:
    public: true
    arguments:
      - '@Xapi\FsManager\Snapshot\ScopedWalker'

  Xapi\FsManager\Snapshot\Walker:
    public: true

  Xapi\FsManager\Snapshot\ScopedWalker:
    public: true
    arguments:
      - '@Xapi\FsManager\Snapshot\Walker'
      - '%xapi.fs_manager.root_folder%'
